name: Package Review
# https://github.com/kaste/st_package_reviewer/tree/main/gh_action_package

on:
    workflow_dispatch:

jobs:
  package-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Review artifact for Package Control
        uses: kaste/st_package_reviewer/gh_action_package@v1
        with:
          package-name: 'HTML (C#)'
          st-build: 4204
          repo: ''  # Skip tags check
