name: Syntax Tests
# https://github.com/sublimetext/syntax-test-action

on:
  push:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - build: latest
            packages: master
          - build: stable
            packages: master
          - build: 4114  # Need HTML with `script_content_begin` for override
            packages: binary
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
          package_name: HTML (C#)
